# Generated by Django 4.0 on 2022-02-24 19:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='assignee',
        ),
        migrations.AlterField(
            model_name='issue',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
